apiVersion: apps/v1
kind: Deployment
metadata:
  name: uiapp-deployment
  namespace: app
spec:
  replicas: 3  # Number of desired replicas
  selector:
    matchLabels:
      app: uiapp
  strategy:
   type: RollingUpdate
   rollingUpdate:
     maxUnavailable: 2 
     maxSurge: 1     
  template:
    metadata:
      labels:
        app: uiapp
    spec:
      containers:
      - name: uiapp
        image: apatranobis59/uiapp:latest
        resources:
          requests:
            memory: "350Mi"
            cpu: "50m"
          limits:
            memory: "400Mi"
            cpu: "100m" 
        ports:
        - containerPort: 3000  # Port your application listens on