apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotstar-deployment
spec:
  replicas: 3  # Number of desired replicas
  selector:
    matchLabels:
      app: hotstar
  strategy:
   type: RollingUpdate
   rollingUpdate:
     maxUnavailable: 2 
     maxSurge: 1      
  template:
    metadata:
      labels:
        app: hotstar
    spec:
      containers:
      - name: hotstar
        image: apatranobis59/hotstar:latest
        resources:
          requests:
            memory: "200Mi"
            cpu: "250m"
          limits:
            memory: "300Mi"
            cpu: "500m" 
        ports:
        - containerPort: 3000  # Port your application listens on
