apiVersion: v1
kind: Service
metadata:
  name: uiapp-service
  namespace: app
spec:
  selector:
    app: uiapp
  ports:
    - protocol: TCP
      port: 80  # Port exposed by the service externally (outside the cluster)
      targetPort: 3000  # Port your application listens on inside the pods
  type: LoadBalancer
